# Generated by Django 3.2 on 2021-05-11 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentT',
            fields=[
                ('assessment_id', models.CharField(max_length=38, primary_key=True, serialize=False)),
                ('assessmenttype', models.CharField(blank=True, db_column='assessmentType', max_length=1, null=True)),
                ('assessmentweightage', models.DecimalField(blank=True, db_column='assessmentWeightage', decimal_places=3, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'assessment_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoevaluationT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comarksattainable', models.IntegerField(blank=True, db_column='coMarksAttainable', null=True)),
                ('comarksobtained', models.IntegerField(blank=True, db_column='coMarksObtained', null=True)),
                ('cobenchmark', models.DecimalField(blank=True, db_column='coBenchmark', decimal_places=3, max_digits=10, null=True)),
                ('coachievementstatus', models.CharField(blank=True, db_column='coAchievementStatus', max_length=1, null=True)),
            ],
            options={
                'db_table': 'coevaluation_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoT',
            fields=[
                ('co_id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('codescription', models.TextField(blank=True, db_column='coDescription', null=True)),
            ],
            options={
                'db_table': 'co_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoursehistoryT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'coursehistory_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseT',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('coursename', models.CharField(blank=True, db_column='courseName', max_length=40, null=True)),
                ('totalcredits', models.IntegerField(blank=True, db_column='totalCredits', null=True)),
            ],
            options={
                'db_table': 'course_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumT',
            fields=[
                ('curriculum_id', models.CharField(max_length=38, primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, max_length=2, null=True)),
                ('effectivedate', models.DateField(blank=True, db_column='effectiveDate', null=True)),
                ('expirationdate', models.DateField(blank=True, db_column='expirationDate', null=True)),
            ],
            options={
                'db_table': 'curriculum_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentT',
            fields=[
                ('department_id', models.CharField(max_length=38, primary_key=True, serialize=False)),
                ('deparmentname', models.CharField(blank=True, db_column='deparmentName', max_length=50, null=True)),
                ('fname', models.CharField(blank=True, db_column='FName', max_length=15, null=True)),
                ('lname', models.CharField(blank=True, db_column='LName', max_length=15, null=True)),
            ],
            options={
                'db_table': 'department_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacultyT',
            fields=[
                ('faculty_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, db_column='FName', max_length=15, null=True)),
                ('lname', models.CharField(blank=True, db_column='LName', max_length=15, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=40, null=True)),
                ('contact', models.CharField(blank=True, db_column='Contact', max_length=13, null=True)),
            ],
            options={
                'db_table': 'faculty_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PloevaluationT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plobenchmark', models.DecimalField(blank=True, db_column='ploBenchmark', decimal_places=3, max_digits=10, null=True)),
                ('ploachievementstatus', models.CharField(blank=True, db_column='ploAchievementStatus', max_length=1, null=True)),
            ],
            options={
                'db_table': 'ploevaluation_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlohistoryT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plohistory_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PloT',
            fields=[
                ('plo_id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('ploname', models.CharField(db_column='ploName', max_length=50)),
                ('plodescription', models.TextField(blank=True, db_column='ploDescription', null=True)),
            ],
            options={
                'db_table': 'plo_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramT',
            fields=[
                ('program_id', models.CharField(max_length=38, primary_key=True, serialize=False)),
                ('programname', models.CharField(blank=True, db_column='programName', max_length=50, null=True)),
                ('totalcredits', models.IntegerField(blank=True, db_column='totalCredits', null=True)),
                ('programlevel', models.CharField(blank=True, db_column='programLevel', max_length=1, null=True)),
            ],
            options={
                'db_table': 'program_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionT',
            fields=[
                ('question_id', models.CharField(max_length=38, primary_key=True, serialize=False)),
                ('marksattainable', models.IntegerField(blank=True, db_column='marksAttainable', null=True)),
            ],
            options={
                'db_table': 'question_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolT',
            fields=[
                ('school_id', models.CharField(max_length=38, primary_key=True, serialize=False)),
                ('schoolname', models.CharField(blank=True, db_column='schoolName', max_length=50, null=True)),
                ('fname', models.CharField(blank=True, db_column='FName', max_length=15, null=True)),
                ('lname', models.CharField(blank=True, db_column='LName', max_length=15, null=True)),
            ],
            options={
                'db_table': 'school_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectionT',
            fields=[
                ('section_id', models.CharField(max_length=38, primary_key=True, serialize=False)),
                ('sectionno', models.IntegerField(blank=True, db_column='sectionNo', null=True)),
                ('timeslot', models.TimeField(blank=True, db_column='timeSlot', null=True)),
                ('days', models.CharField(blank=True, max_length=2, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('session', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'section_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentcourseenrollmentT',
            fields=[
                ('courseenrollment_id', models.CharField(db_column='courseEnrollment_id', max_length=38, primary_key=True, serialize=False)),
                ('classattended', models.IntegerField(blank=True, db_column='classAttended', null=True)),
                ('totalclasses', models.IntegerField(blank=True, db_column='totalClasses', null=True)),
            ],
            options={
                'db_table': 'studentcourseenrollment_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentT',
            fields=[
                ('student_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, db_column='Fname', max_length=15, null=True)),
                ('lname', models.CharField(blank=True, db_column='Lname', max_length=15, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=25, null=True)),
                ('contact', models.CharField(blank=True, db_column='Contact', max_length=13, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('studenttype', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'student_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniversityT',
            fields=[
                ('u_id', models.CharField(db_column='U_ID', max_length=38, primary_key=True, serialize=False)),
                ('uname', models.CharField(blank=True, db_column='UName', max_length=50, null=True)),
                ('vcfname', models.CharField(blank=True, db_column='VCFName', max_length=15, null=True)),
                ('vclname', models.CharField(blank=True, db_column='VCLName', max_length=15, null=True)),
            ],
            options={
                'db_table': 'university_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VchistoryT',
            fields=[
                ('u', models.OneToOneField(db_column='U_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='SPM.universityt')),
                ('fname', models.CharField(db_column='Fname', max_length=15)),
                ('lname', models.CharField(db_column='Lname', max_length=15)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vchistory_t',
                'managed': False,
            },
        ),
    ]
