# Generated by Django 3.2 on 2021-05-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemestermappingT',
            fields=[
                ('session', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('startdate', models.DateField(blank=True, db_column='startDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='endDate', null=True)),
            ],
            options={
                'db_table': 'semestermapping_t',
                'managed': False,
            },
        ),
    ]
